## Demonstrating how the mathematics of the Matrices look like
There are various matrix operations. We will cover how they are done in code.
- Element-wise Matrix Addition
- Element-wise Matrix Subtraction
- Element-wise Matrix Multiplication
- Dot-Product
- Cross-Product

For Neural Network, the matrix operation used is the **Dot-Product**.

However, do note that the codes here are all purely for demonstration purposes, for your understanding. It is very unlikely that you will need to implement these matrix operations yourself when building Neural Networks, since DL libraries like PyTorch, TensorFlow and Keras, which you will most likely use when building Neural Networks, has already integrated all these in their ready-made API functions.

### Why this file?
To make computation simpler, NN uses matrix operations to simplify and 'summarise' the operations into fewer notation, hence knowledge here will be used in the implementation of Gradient Descent Optimization algorithms for NN.

In [6]:
import numpy as np

### Element-wise Matrix Addition

In [10]:
# Our sample 2D matrices, implemented with NumPy
revenue = np.array([
    [180, 200, 220],
    [24, 36, 40],
    [12, 18, 20]
])

expenses = np.array([
    [80, 90, 100],
    [10, 16, 20],
    [8, 10, 10]
])


profit = revenue + expenses
print(profit)

[[260 290 320]
 [ 34  52  60]
 [ 20  28  30]]


### Element-wise Matrix Subtraction

In [8]:
# Our sample 2D matrices, implemented with NumPy
revenue = np.array([
    [180, 200, 220],
    [24, 36, 40],
    [12, 18, 20]
])

expenses = np.array([
    [80, 90, 100],
    [10, 16, 20],
    [8, 10, 10]
])


profit = revenue - expenses
print(profit)

[[100 110 120]
 [ 14  20  20]
 [  4   8  10]]


### Element-wise Matrix Multiplication

In [16]:
# Our sample 2D matrices, implemented with NumPy

# This is an example of NumPy Broadcasting, which describes how NumPy treats arrays with different shapes during 
# arithmetic operations. Subject to certain constraints, the smaller array is “broadcast”/expanded across the larger 
# array so that they have compatible shapes.

# i.e. Here, since 'price_per_unit' and 'units' are not same shape, NumPy will expand the smaller array to match the 
# size of the larger array. So NumPy will do element-wise Matrix Multiplication here as if:
    # price_per_unit = np.array([[1000, 400, 1200], [1000, 400, 1200], [1000, 400, 1200]])
price_per_unit = np.array([1000, 400, 1200])

units = np.array([
    [30, 40, 50],
    [5,  10, 15],
    [2,   5,  7]
])

print(price_per_unit * units)

[[30000 16000 60000]
 [ 5000  4000 18000]
 [ 2000  2000  8400]]


## Dot-Product

In [22]:
# Our sample 2D matrices, implemented with NumPy
price_per_unit = np.array([1000, 400, 1200])

units = np.array([
    [30, 40, 50],
    [5,  10, 15],
    [2,   5,  7]
])

print(np.dot(price_per_unit, units))

[34400 50000 64400]


## Cross-Product

In [19]:
# Our sample 2D matrices, implemented with NumPy

# This is an example of NumPy Broadcasting, which describes how NumPy treats arrays with different shapes during 
# arithmetic operations. Subject to certain constraints, the smaller array is “broadcast”/expanded across the larger 
# array so that they have compatible shapes.

# i.e. Here, since 'price_per_unit' and 'units' are not same shape, NumPy will expand the smaller array to match the 
# size of the larger array. So NumPy will do element-wise Matrix Multiplication here as if:
    # price_per_unit = np.array([[1000, 400, 1200], [1000, 400, 1200], [1000, 400, 1200]])
price_per_unit = np.array([1000, 400, 1200])

units = np.array([
    [30, 40, 50],
    [5,  10, 15],
    [2,   5,  7]
])

print(np.cross(price_per_unit, units))

[[-28000 -14000  28000]
 [ -6000  -9000   8000]
 [ -3200  -4600   4200]]


# Excercises

## Excercise 1
Below is some indian companies revenues in US dollars. Using numpy can you convert this into Indian rupees? 1 USD = 75 INR
| Company             | FY 2018 | FY 2019 | FY 2020 |
| ------------------- | ------- | ------- | ------- |
| Reliance Industries | 200     | 220     | 250     |
| Infosys             | 68      | 79      | 105     |
| TCS                 | 110     | 140     | 180     |
| Wipro               | 80      | 85      | 90      |


In [26]:
revenue = np.array([
    [200,220,250],
    [68,79,105],
    [110,140,180],
    [80,85,90]
])

indian_rupees = 75

indian_rupees_revenue = revenue * indian_rupees
print(indian_rupees_revenue)

[[15000 16500 18750]
 [ 5100  5925  7875]
 [ 8250 10500 13500]
 [ 6000  6375  6750]]


## Excercise 2
Divine flowers is a flower shop that sells different type of flowers. Below is the table showing how many flowers of each type they sold in different months. Also given are the prices of one flower each. Using this find out their total sales in every month.
| Flower Type | Jan | Feb | March |
| ----------- | --- | --- | ----- |
| Roses       | 50  | 60  | 25    |
| Lotus       | 10  | 13  | 5     |
| Sunflower   | 40  | 70  | 52    |

| Flower Type | Price |
| ----------- | ----- |
| Roses       | 20    |
| Lotus       | 30    |
| Sunflower   | 15    |


In [34]:
prices = np.array([
    [50,10,40],
    [60,13,70],
    [25,5,52]
])

price_each_type = np.array([20,30,15])

print(np.dot(prices, price_each_type))



[1900 2640 1430]
